#! /bin/sh

# recompile
#mvn --quiet package

# detect color terminals
OPTION=''
COLORS=$(tput colors 2> /dev/null)
if [ $? = 0 ] && [ $COLORS -gt 2 ]; then
    OPTION='-L logback-ansi.xml'
fi

mvn --quiet exec:java -Dexec.args="$OPTION $*"
